language: node_js
node_js:
  - "node"

cache: npm

script: npm run build

deploy:
provider: pages
skip_cleanup: true
github_token: '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'
local_dir: dist
on:
  branch: master
