language: node_js
node_js:
  - "node"

cache: npm

script: npm run build

deploy:
provider: pages
skip_cleanup: true
github_token: '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'
local_dir: dist
on:
  branch: master
